import type { Metadata } from "next";
import { Oswald, Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/ui/navbar";
import { LINKS, SOCIALMEDIA } from "@/lib/constants";
import { Footer } from "@/components/ui/footer";

const oswald = Oswald({
  weight: "400", // Oswald only has one weight
  subsets: ["latin"],
  display: "swap",
  variable: "--font-oswald",
});

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-theme="black"
      className={`${poppins.variable} ${oswald.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col md:items-center">
        <div className="w-full md:w-10/12">
          <header className="sticky top-0 z-50">
            <Navbar
              name="Fausto Durazo"
              links={LINKS}
              socialMedia={SOCIALMEDIA}
            />
          </header>
          <main>{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
